Repository dita-ot/dita-ot, pull requests merged in 2018-07, with the labels that each got.

#3005 Fixes missing $file-being-processed parameter in xsl/preprocess/mapre…
  src/main/java/org/dita/dost/module/MaprefModule.java
Labels: P1, bug, preprocess, preprocess2

#1831 Fail Ant build if PDF rendering fails #1414
  src/main/plugins/org.dita.pdf2.axf/build_axf.xml
  src/main/plugins/org.dita.pdf2.fop/build_fop.xml
  src/main/plugins/org.dita.pdf2.xep/build_xep.xml
  src/main/plugins/org.dita.pdf2/resource/messages.xml
Labels: P2, enhancement, pdf

#3012 Fix Antenna House log processor #2662
  src/main/plugins/org.dita.pdf2.axf/build.gradle
  src/main/plugins/org.dita.pdf2.axf/src/org/dita/dost/pdf2/AhfLogProcessorTask.java
  src/main/plugins/org.dita.pdf2.axf/test/org/dita/dost/pdf2/AhfLogProcessorTaskTest.java
Labels: P2, bug, pdf

#3015 Fix missing src for copy-to target
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
Labels: P1, bug, preprocess2

#3010 Fix map reader handling for non-DITA resources #2855
  src/main/java/org/dita/dost/module/reader/MapReaderModule.java
  src/test/java/org/dita/dost/module/reader/MapReaderModuleTest.java
Labels: P2, bug, preprocess2

#3017 Update troff plugin version
  build.gradle
Labels: P2, dependency, feature, troff

#3024 Fix configuration file generation and reading
  build.gradle
  src/main/java/org/dita/dost/util/Configuration.java
  src/main/plugins/org.dita.base/build_init.xml
Labels: P2, bug, platform

#3020 Refactor HTML5 CSS configuration
  build.gradle
  src/main/plugins/org.dita.html5/build_dita2html5_template.xml
  src/test/java/org/dita/dost/AbstractIntegrationTest.java
  src/test/java/org/dita/dost/IntegrationTestHtml5.java
  src/test/resources/html5_css/exp/html5/topic.html
  src/test/resources/html5_css/src/custom.css
  src/test/resources/html5_css/src/topic.dita
  src/test/resources/html5_cssExternal/exp/html5/topic.html
  src/test/resources/html5_cssExternal/src/topic.dita
  src/test/resources/html5_csspath/exp/html5/topic.html
  src/test/resources/html5_csspath/src/custom.css
  src/test/resources/html5_csspath/src/topic.dita
Labels: P2, enhancement, html5

#3031 LQ should indent by default #3009
  src/main/plugins/org.dita.pdf2/cfg/fo/attrs/topic-attr.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/topic.xsl
Labels: P2, enhancement, pdf
