Repository dita-ot/dita-ot, pull requests merged in 2018-06, with the labels that each got.

#2984 Feature/newmarkers
  src/main/plugins/org.dita.pdf2/xsl/fo/commons.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/glossary.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/index.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/links.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/lot-lof.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/pr-domain.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/preface.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/tables.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/toc.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/topic.xsl
Labels: P2, enhancement, pdf

#2967 Use SLF4J with FOP
  src/main/config/logback.xml
  src/main/plugins/org.dita.pdf2.fop/build.gradle
  src/main/plugins/org.dita.pdf2.fop/plugin.xml
Labels: P2, enhancement, pdf/fop

#2982 Update LwDITA plugin to 2.0.4
  build.gradle
Labels: P3, dependency, enhancement

#2991 Update Gradle wrapper to 4.7
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build, dependency, enhancement

#2986 Update Java dependencies
  build.gradle
  src/main/java/org/dita/dost/writer/ImageMetadataFilter.java
Labels: P2, dependency, enhancement

#2928 New test case with mapref to conref
  src/test/java/org/dita/dost/IntegrationTest.java
  src/test/resources/mapref_to_conref/exp/preprocess/alsorealcontent.dita
  src/test/resources/mapref_to_conref/exp/preprocess/indirect.ditamap
  src/test/resources/mapref_to_conref/exp/preprocess/indirectcontainer.dita
  src/test/resources/mapref_to_conref/exp/preprocess/root.ditamap
  src/test/resources/mapref_to_conref/exp/preprocess/targetmap.ditamap
  src/test/resources/mapref_to_conref/src/alsorealcontent.dita
  src/test/resources/mapref_to_conref/src/indirect.ditamap
  src/test/resources/mapref_to_conref/src/indirectcontainer.dita
  src/test/resources/mapref_to_conref/src/root.ditamap
  src/test/resources/mapref_to_conref/src/targetmap.ditamap
Labels: enhancement, preprocess, preprocess2, testing

#2994 Update Gradle wrapper to 4.8
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build, dependency, enhancement

#2993 Update LwDITA plugin dependency to 2.0.5
  build.gradle
Labels: dependency, enhancement
