Repository dita-ot/dita-ot, pull requests merged in 2019-09, with the labels that each got.

#3354 Update Ant to 1.10.6
  build.gradle
  src/main/java/org/dita/dost/ant/types/JobSourceSet.java
Labels: dependency, enhancement

#3356 Avoid crash for invalid table input
  src/main/plugins/org.dita.html5/xsl/functions.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/tablefunctions.xsl
Labels: bug, plugin/html5, plugin/xhtml, priority/medium

#3362 Update to Jackson 2.9.9
  build.gradle
Labels: dependency, enhancement, priority/medium

#3363 Remove TocJS plugin from default distribution
  build.gradle
Labels: dependency, enhancement, priority/low
