Repository dita-ot/dita-ot, pull requests merged in 2019-07, with the labels that each got.

#3336 Fix indentation of Swiss German warning string
  src/main/plugins/org.dita.base/xsl/common/strings-de-ch.xml
Labels: bug, priority/low

#3325 Support passthrough without @att and @val
  src/main/plugins/org.dita.html5/xsl/topic.xsl
  src/test/java/org/dita/dost/IntegrationTestHtml5.java
  src/test/resources/html5_ditaval/exp/html5/all.html
  src/test/resources/html5_ditaval/exp/html5/index.html
  src/test/resources/html5_ditaval/src/all.dita
  src/test/resources/html5_ditaval/src/all.ditamap
  src/test/resources/html5_ditaval/src/all.ditaval
Labels: bug, plugin/html5, priority/medium

#3338 Update to LwDITA 2.3.0
  build.gradle
Labels: bug, dependency, priority/medium

#3329 Travis CI parallel jobs
  .travis.yml
Labels: CI, enhancement
