Repository dita-ot/dita-ot, pull requests merged in 2019-04, with the labels that each got.

#3269 Fix bugs in project parsing and missing features
  build.gradle
  gradle/dist.gradle
  src/main/java/org/dita/dost/invoker/Main.java
  src/main/java/org/dita/dost/project/Project.java
  src/main/java/org/dita/dost/project/ProjectBuilder.java
  src/main/java/org/dita/dost/project/ProjectFactory.java
  src/main/java/org/dita/dost/project/XmlReader.java
  src/test/java/org/dita/dost/project/ProjectBuilderTest.java
  src/test/java/org/dita/dost/project/ProjectFactoryTest.java
  src/test/java/org/dita/dost/project/ProjectTest.java
  src/test/java/org/dita/dost/project/XmlReaderTest.java
  src/test/resources/org/dita/dost/project/common.json
  src/test/resources/org/dita/dost/project/common.yaml
  src/test/resources/org/dita/dost/project/product.json
  src/test/resources/org/dita/dost/project/product.yaml
  src/test/resources/org/dita/dost/project/recursive.json
  src/test/resources/org/dita/dost/project/root.json
  src/test/resources/org/dita/dost/project/root.yaml
  src/test/resources/org/dita/dost/project/simple.json
  src/test/resources/org/dita/dost/project/simple.yaml
Labels: enhancement, priority/medium, project

#3275 Simplify input configuration in project files
  src/main/java/org/dita/dost/project/Project.java
  src/main/java/org/dita/dost/project/ProjectBuilder.java
  src/main/java/org/dita/dost/project/XmlReader.java
  src/main/resources/project.rnc
  src/test/java/org/dita/dost/project/XmlReaderTest.java
  src/test/resources/org/dita/dost/project/common.json
  src/test/resources/org/dita/dost/project/common.xml
  src/test/resources/org/dita/dost/project/common.yaml
  src/test/resources/org/dita/dost/project/simple.json
  src/test/resources/org/dita/dost/project/simple.xml
  src/test/resources/org/dita/dost/project/simple.yaml
Labels: enhancement, project

#3248 Fix duplicate conref target message
  src/main/plugins/org.dita.base/xsl/preprocess/conrefImpl.xsl
Labels: bug, priority/low

#3251 Fix plugin param types
  src/main/plugins/org.dita.base/plugin.xml
  src/main/plugins/org.dita.html5/plugin.xml
  src/main/plugins/org.dita.xhtml/plugin.xml
Labels: bug, priority/medium

#3249 Fix table numbering when draft excluded
  src/main/plugins/org.dita.pdf2/xsl/fo/commons.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/lot-lof.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/tables.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/topic.xsl
Labels: bug, plugin/pdf, priority/medium

#3277 Change registry to use HTTPS
  src/main/config/configuration.properties
Labels: feature, plugin-integration, priority/high

#3278 Change registry to use HTTPS
  src/main/config/configuration.properties
Labels: enhancement, plugin-integration, priority/high

#3285 Refactor main class argument parser
  src/main/java/org/dita/dost/invoker/ArgumentParser.java
  src/main/java/org/dita/dost/invoker/Arguments.java
  src/main/java/org/dita/dost/invoker/Main.java
  src/test/java/org/dita/dost/invoker/ArgumentParserTest.java
Labels: CLI, enhancement, priority/medium

#3288 Remove obsolete demo build script
  build.gradle
  src/main/build_demo.xml
Labels: enhancement, priority/medium

#3295 Fix plug-in installation with multiple plug-ins #3294
  src/main/java/org/dita/dost/ant/PluginInstallTask.java
Labels: enhancement, plugin-integration, priority/medium
