Repository dita-ot/dita-ot, pull requests merged in 2020-11, with the labels that each got.

#3625 Fix JobSourceSet cases where src is null
  src/main/java/org/dita/dost/ant/types/JobSourceSet.java
Labels: bug, preprocess, priority/medium

#3626 Fix current file directory URI resolution when file doesn't exist
  src/main/java/org/dita/dost/writer/ChunkTopicParser.java
  src/main/java/org/dita/dost/writer/TopicRefWriter.java
Labels: bug, preprocess/chunking, priority/medium

#3630 Fix for #3558, update PDF libraries
  src/main/plugins/org.dita.pdf2.fop/build.gradle
  src/main/plugins/org.dita.pdf2.fop/plugin.xml
Labels: dependency, enhancement, plugin/pdf/fop, priority/medium

#3634 HTMLHelp: Remove invalid code remnant (#3627)
  src/main/plugins/org.dita.htmlhelp/xsl/map2htmlhelp/map2hhcImpl.xsl
Labels: bug, plugin/htmlhelp

#3629 Update Gradle wrapper to 6.7
  .github/workflows/gradle-wrapper-validation.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependency

#3632 HTML5: Move hard-coded styles to Sass partials
  src/main/plugins/org.dita.html5/sass/commonltr.scss
  src/main/plugins/org.dita.html5/sass/domains/_hi-d.scss
  src/main/plugins/org.dita.html5/sass/domains/_pr-d.scss
  src/main/plugins/org.dita.html5/sass/domains/_topic.scss
  src/main/plugins/org.dita.html5/xsl/hi-d.xsl
  src/main/plugins/org.dita.html5/xsl/syntax-braces.xsl
  src/main/plugins/org.dita.html5/xsl/topic.xsl
Labels: enhancement, plugin/html5

#3636 Fix repeat count in install and uninstall subcommands
  src/main/java/org/dita/dost/invoker/Main.java
Labels: CLI, bug, priority/medium

#3640 Add GitHub Actions for unit tests
  .github/workflows/test.yml
  .travis.yml
Labels: CI, feature

#3642 Remove disabled pdf2.index.skip param and deprecate old PDF indexing
  src/main/plugins/org.dita.pdf2/build_template.xml
  src/main/plugins/org.dita.pdf2/plugin.xml
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexCollator.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexComparator.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexEntry.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexEntryFoundListener.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexGroup.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexGroupProcessor.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexPreprocessResult.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexPreprocessor.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/IndexPreprocessorTask.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/ProcessException.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/configuration/CharRange.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/configuration/ConfigEntry.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/configuration/ConfigEntryImpl.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/configuration/IndexConfiguration.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/configuration/ParseException.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/util/IndexDitaProcessor.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/util/IndexEntryImpl.java
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/index2/util/IndexStringProcessor.java
Labels: enhancement, plugin/pdf, priority/medium
