Repository dita-ot/dita-ot, pull requests merged in 2020-12, with the labels that each got.

#3643 Update dependencies
  build.gradle
Labels: dependency, enhancement

#3628 Improve topicref writer tests
  src/main/java/org/dita/dost/writer/TopicRefWriter.java
  src/test/java/org/dita/dost/writer/TopicRefWriterTest.java
Labels: enhancement, preprocess/chunking, priority/medium

#3644 Catch exception from reading JPEG image #3604
  src/main/java/org/dita/dost/writer/ImageMetadataFilter.java
Labels: bug, plugin/html5, priority/medium

#3645 Add RELAX NG schemas to resources catalog
  build.gradle
  src/main/plugins/org.dita.base/catalog-dita_template.xml
  src/main/resources/catalog.xml
Labels: enhancement

#3651 Switch rotated table entries to 'vertical-rl' mode
  src/main/plugins/org.dita.html5/sass/_tables.scss
Labels: plugin/html5

#3652 Add support for multimedia oasis-tcs/dita#351
  src/main/plugins/org.dita.html5/xsl/topic.xsl
Labels: feature, plugin/html5, priority/medium

#3657 Fix NPE when initializing store
  src/main/java/org/dita/dost/ant/ExtensibleAntInvoker.java
  src/test/java/org/dita/dost/ant/ExtensibleAntInvokerTest.java
Labels: bug, priority/medium
