Repository dita-ot/dita-ot, pull requests merged in 2020-09, with the labels that each got.

#3567 Fix sibling keyscope cascading
  src/main/java/org/dita/dost/reader/KeyrefReader.java
  src/test/java/org/dita/dost/reader/TestKeyrefReader.java
Labels: bug, preprocess/keyref, priority/medium

#3575 Fix table normalization for multiple groups and broken tables
  src/main/config/messages_template.xml
  src/main/java/org/dita/dost/writer/NormalizeTableFilter.java
  src/test/java/org/dita/dost/writer/NormalizeTableFilterTest.java
  src/test/resources/NormalizeTableFilterTest/exp/broken.dita
  src/test/resources/NormalizeTableFilterTest/exp/multiGroup.dita
  src/test/resources/NormalizeTableFilterTest/src/broken.dita
  src/test/resources/NormalizeTableFilterTest/src/multiGroup.dita
  src/test/resources/messages.xml
  src/test/resources/messages_en_US.properties
Labels: bug, preprocess, priority/medium

#3574 Prefer public IDs when comparing grammar descriptors
  src/main/java/org/dita/dost/util/XMLGrammarPoolImplUtils.java
  src/test/java/org/dita/dost/util/XMLGrammarPoolImplUtilsTest.java
Labels: bug, preprocess

#3583 Use BufferedWriter to output Job for 200 fold performance improvement
  src/main/java/org/dita/dost/util/Job.java
  src/test/java/org/dita/dost/util/JobTest.java
Labels: enhancement

#3570 Use concurrent sets or queues
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
Labels: enhancement

#3569 Cache DitaClass instances
  src/main/java/org/dita/dost/module/ChunkModule.java
  src/main/java/org/dita/dost/reader/CopyToReader.java
  src/main/java/org/dita/dost/reader/GenListModuleReader.java
  src/main/java/org/dita/dost/util/Constants.java
  src/main/java/org/dita/dost/util/DitaClass.java
  src/main/java/org/dita/dost/writer/ConrefPushParser.java
  src/main/java/org/dita/dost/writer/DebugFilter.java
  src/main/java/org/dita/dost/writer/DitaWriterFilter.java
  src/main/java/org/dita/dost/writer/ExportAnchorsFilter.java
  src/main/java/org/dita/dost/writer/KeyrefPaser.java
  src/main/java/org/dita/dost/writer/ProfilingFilter.java
  src/main/java/org/dita/dost/writer/TopicFragmentFilter.java
  src/test/java/org/dita/dost/util/DitaClassTest.java
  src/test/java/org/dita/dost/util/XMLUtilsTest.java
Labels: enhancement

#3579 Enable nonworking dita.xsl.html5.cover extension point (#2981)
  src/main/plugins/org.dita.html5/xsl/cover.xsl
  src/main/plugins/org.dita.html5/xsl/map2html5-coverImpl_template.xsl
Labels: bug, plugin/html5, priority/medium

#3585 Use S9api in keyref processing
  src/main/java/org/dita/dost/log/MessageBean.java
  src/main/java/org/dita/dost/module/ChunkModule.java
  src/main/java/org/dita/dost/module/KeyrefModule.java
  src/main/java/org/dita/dost/reader/KeyrefReader.java
  src/main/java/org/dita/dost/util/DitaClass.java
  src/main/java/org/dita/dost/util/KeyDef.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/main/java/org/dita/dost/writer/KeyrefPaser.java
  src/test/java/org/dita/dost/module/KeyrefModuleTest.java
  src/test/java/org/dita/dost/reader/TestKeyrefReader.java
  src/test/java/org/dita/dost/writer/KeyrefPaserTest.java
Labels: enhancement, preprocess/keyref, priority/medium

#3591 Allow FOP to generate changebars
  src/main/plugins/org.dita.pdf2.fop/xsl/fo/flagging_fop.xsl
  src/main/plugins/org.dita.pdf2.fop/xsl/fo/topic2fo_shell_fop_template.xsl
Labels: feature, plugin/pdf/fop

#3593 Fix build init order to initialise project after temp dir
  src/main/plugins/org.dita.base/build_init.xml
Labels: bug, priority/high

#3595 Extract Dublin Core metadata field generation to own plug-in
  src/main/plugins/org.dita.html5/xsl/dita2html5Impl_template.xsl
  src/main/plugins/org.dita.html5/xsl/get-meta.xsl
  src/main/plugins/org.dita.html5/xsl/topic.xsl
  src/test/resources/html5_css/exp/html5/topic.html
  src/test/resources/html5_cssExternal/exp/html5/topic.html
  src/test/resources/html5_csspath/exp/html5/topic.html
  src/test/resources/html5_ditaval/exp/html5/all.html
  src/test/resources/html5_ditaval/exp/html5/index.html
Labels: enhancement, plugin/html5, priority/medium
