Repository dita-ot/dita-ot, pull requests merged in 2021-02, with the labels that each got.

#3696 Transform URIs which might have anchor
  src/main/java/org/dita/dost/store/AbstractStore.java
  src/test/java/org/dita/dost/store/StreamStoreTest.java
Labels: bug, preprocess, priority/medium

#3697 Use sax source directly instead of toString() representation
  src/main/java/org/dita/dost/module/CleanPreprocessModule.java
  src/test/java/org/dita/dost/module/CleanPreprocessModuleTest.java
Labels: bug, preprocess, priority/medium

#3698 Take into account URI may not be file when checking its existence
  src/main/java/org/dita/dost/store/StreamStore.java
  src/test/java/org/dita/dost/store/StreamStoreTest.java
Labels: bug, preprocess, priority/medium

#3699 Properly compute absolute locations in merge map and topic parsers
  src/main/java/org/dita/dost/reader/MergeMapParser.java
  src/main/java/org/dita/dost/reader/MergeTopicParser.java
  src/test/java/org/dita/dost/reader/MergeMapParserTest.java
  src/test/java/org/dita/dost/reader/MergeTopicParserTest.java
Labels: bug, plugin/pdf, priority/medium

#3701 Fix copy of topicmeta between keydef and keyref
  src/main/java/org/dita/dost/reader/KeyrefReader.java
  src/test/java/org/dita/dost/reader/TestKeyrefReader.java
  src/test/resources/TestKeyrefReader/src/intermediaryKeyref.ditamap
Labels: bug, preprocess/keyref, priority/medium

#3695 Fix resolution of custom resources in PDF pre processor task
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/i18n/PreprocessorTask.java
Labels: bug, plugin/pdf, priority/medium

#3706 Fix calling unset logger
  src/main/java/org/dita/dost/Processor.java
  src/test/java/org/dita/dost/ProcessorTest.java
Labels: bug, priority/medium
