Repository dita-ot/dita-ot, pull requests merged in 2022-11, with the labels that each got.

#4037 Take into account root chunk override earlier
  src/main/java/org/dita/dost/reader/ChunkMapReader.java
  src/test/java/org/dita/dost/reader/ChunkMapReaderTest.java
  src/test/resources/ChunkMapReaderTest/src/mapNoChunk.ditamap
Labels: bug, priority/medium, preprocess

#4038 Fix parser configuration
  src/main/java/org/dita/dost/module/DebugAndFilterModule.java
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/SourceReaderModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/util/XMLUtils.java
Labels: bug, priority/medium, preprocess2

#4039 Fix image default scope
  src/main/java/org/dita/dost/reader/GenListModuleReader.java
  src/test/java/org/dita/dost/reader/TestGenListModuleReader.java
Labels: bug, priority/medium, preprocess

#4040 Bump OASIS 2.0 grammar to the latest draft
  build.gradle
Labels: enhancement, DITA 2.0

#4044 Add PDF theme plug-in as bundled plug-in
  build.gradle
Labels: feature, priority/medium

#4045 Update bundled LwDITA plug-in to 3.3
  build.gradle
Labels: priority/medium, dependency, plugin/lwdita

#4046 Change default encoding for coderefs to UTF-8
  src/main/config/configuration.properties
Labels: feature, priority/medium, preprocess/coderef

#4049 Add directed graph using adjacent matrix
  src/main/java/org/dita/dost/util/Graph.java
  src/test/java/org/dita/dost/util/GraphTest.java
Labels: enhancement

#4052 Add directed graph for URIs
  src/main/java/org/dita/dost/util/Graph.java
  src/main/java/org/dita/dost/util/UriGraph.java
  src/test/java/org/dita/dost/util/UriGraphTest.java
Labels: enhancement

#4030 filter <indexterm> elements when computing <xref> target text for `pdf2`
  src/main/plugins/org.dita.pdf2/xsl/fo/links.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/tables.xsl
Labels: bug, plugin/pdf

#4058 Update jackson-databind for security #4016
  build.gradle
Labels: bug, priority/medium, dependency, security

#4054 PDF2: Remove duplicate `space-before` attribute
  src/main/plugins/org.dita.pdf2/cfg/fo/attrs/topic-attr.xsl
Labels: bug, plugin/pdf, priority/low
