Repository dita-ot/dita-ot, pull requests merged in 2022-02, with the labels that each got.

#3862 Fix #3861 PDF2 i18n-postprocess extension point not working
  src/main/plugins/org.dita.pdf2/xsl/fo/i18n-postprocessImpl.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/i18n-postprocess_template.xsl
Labels: bug, plugin/pdf, priority/medium

#3880 2844 Remove apos and tilde from the array of characters to be escaped.
  src/main/java/org/dita/dost/util/URLUtils.java
  src/test/java/org/dita/dost/util/URLUtilsTest.java
Labels: bug, priority/medium, preprocess

#3881 #3846 Do not append two anchors to target chunked reference.
  src/main/java/org/dita/dost/writer/AbstractChunkTopicParser.java
  src/test/java/org/dita/dost/TestUtils.java
  src/test/java/org/dita/dost/reader/ChunkMapReaderTest.java
  src/test/resources/ChunkMapReaderTest/src/chunkedMap.ditamap
  src/test/resources/ChunkMapReaderTest/src/chunkedTopic.dita
Labels: bug, priority/medium, preprocess/chunking

#3874 fix for #3867: Child navigation links to nested topics are incorrect/missing if there is a <ph keyref/>
  src/main/java/org/dita/dost/module/KeyrefModule.java
  src/test/java/org/dita/dost/module/KeyrefModuleTest.java
  src/test/resources/KeyrefModuleTest/src/test3.ditamap
Labels: bug, priority/medium, preprocess/keyref

#3883 3882 Change and add translations.
  src/main/plugins/org.dita.base/xsl/common/strings-de-ch.xml
  src/main/plugins/org.dita.base/xsl/common/strings-de-de.xml
  src/main/plugins/org.dita.pdf2/cfg/common/vars/de.xml
  src/main/plugins/org.dita.pdf2/cfg/common/vars/fr.xml
  src/test/resources/lang/exp/xhtml/lang-dech.html
  src/test/resources/lang/exp/xhtml/lang-dede.html
  src/test/resources/lang/exp/xhtml_with_preprocess2/lang-dech.html
  src/test/resources/lang/exp/xhtml_with_preprocess2/lang-dede.html
Labels: priority/medium, enhancement

#3871 In preprocess2 fail on missing image in strict mode
  src/main/java/org/dita/dost/module/reader/TopicReaderModule.java
Labels: bug, priority/medium, preprocess2

#3884 Add missing location to log messages
  src/main/java/org/dita/dost/reader/ConrefPushReader.java
  src/main/java/org/dita/dost/reader/CopyToReader.java
  src/main/java/org/dita/dost/reader/DitaValReader.java
  src/main/java/org/dita/dost/reader/KeydefFilter.java
  src/main/java/org/dita/dost/reader/MergeMapParser.java
  src/main/java/org/dita/dost/writer/ConkeyrefFilter.java
  src/main/java/org/dita/dost/writer/ValidationFilter.java
  src/main/java/org/dita/dost/writer/include/IncludeText.java
Labels: bug, priority/medium

#3892 Support query and fragment parts in image references
  src/main/java/org/dita/dost/ant/types/JobSourceSet.java
  src/main/java/org/dita/dost/util/URLUtils.java
  src/main/java/org/dita/dost/writer/ValidationFilter.java
  src/test/java/org/dita/dost/module/TestGenMapAndTopicListModule.java
  src/test/java/org/dita/dost/util/URLUtilsTest.java
  src/test/resources/TestGenMapAndTopicListModule/src/image/image.dita
Labels: bug, priority/medium, preprocess

#3891 Log invalid character in file include
  src/main/config/messages_template.xml
  src/main/java/org/dita/dost/writer/include/IncludeResolver.java
  src/main/java/org/dita/dost/writer/include/IncludeText.java
  src/main/plugins/org.dita.base/build_preprocess2_template.xml
  src/main/plugins/org.dita.base/build_preprocess_template.xml
  src/test/java/org/dita/dost/writer/include/IncludeResolverTest.java
  src/test/java/org/dita/dost/writer/include/IncludeTextTest.java
  src/test/resources/messages_en_US.properties
Labels: feature, priority/medium, preprocess
