Repository dita-ot/dita-ot, pull requests merged in 2022-07, with the labels that each got.

#3953 Move Docker workflow into Release workflow
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: enhancement, CI

#3933 Fix Windows transformation slowdown for Java 12+ (#3932)
  src/main/bin/ant.bat
  src/main/bin/dita.bat
Labels: platform/windows, enhancement, CLI

#3972 Remove a Unicode quote character in the DOTJ085E message
  src/main/config/messages_template.xml
Labels: bug

#3978 #3969 Properly serialize nodes in xsl message to present in console.
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/test/java/org/dita/dost/util/XMLUtilsTest.java
Labels: bug, priority/medium

#3977 #3366 Fix NPE in FileUtils.getRelativePath
  src/main/java/org/dita/dost/util/FileUtils.java
  src/test/java/org/dita/dost/util/TestFileUtils.java
Labels: bug, priority/medium
