Repository dita-ot/dita-ot, pull requests merged in 2022-08, with the labels that each got.

#3964 Fix for #3724, properly compute absolute references to files.
  src/main/java/org/dita/dost/ant/types/JobSourceSet.java
  src/main/java/org/dita/dost/module/ChunkModule.java
  src/main/java/org/dita/dost/module/ConrefPushModule.java
  src/main/java/org/dita/dost/module/DebugAndFilterModule.java
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/ImageMetadataModule.java
  src/main/java/org/dita/dost/module/KeyrefModule.java
  src/main/java/org/dita/dost/module/MaprefModule.java
  src/main/java/org/dita/dost/module/MoveMetaModule.java
  src/main/java/org/dita/dost/module/XsltModule.java
  src/main/java/org/dita/dost/module/filter/AbstractBranchFilterModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/reader/MergeMapParser.java
  src/main/java/org/dita/dost/reader/MergeTopicParser.java
  src/main/java/org/dita/dost/util/FileUtils.java
  src/test/java/org/dita/dost/util/TestFileUtils.java
Labels: bug, priority/medium, preprocess

#3974 Use #current in mode where possible
  src/main/plugins/org.dita.base/xsl/common/dita-utilities.xsl
  src/main/plugins/org.dita.base/xsl/common/topic2textonly.xsl
  src/main/plugins/org.dita.base/xsl/common/ui-d2textonly.xsl
  src/main/plugins/org.dita.base/xsl/preprocess/conrefImpl.xsl
  src/main/plugins/org.dita.base/xsl/preprocess/maplinkImpl.xsl
  src/main/plugins/org.dita.base/xsl/preprocess/mappullImpl.xsl
  src/main/plugins/org.dita.base/xsl/preprocess/maprefImpl.xsl
  src/main/plugins/org.dita.base/xsl/preprocess/topicpullImpl.xsl
  src/main/plugins/org.dita.html5/xsl/cover.xsl
  src/main/plugins/org.dita.html5/xsl/get-meta.xsl
  src/main/plugins/org.dita.html5/xsl/htmlflag.xsl
  src/main/plugins/org.dita.html5/xsl/map2html5Impl.xsl
  src/main/plugins/org.dita.html5/xsl/nav.xsl
  src/main/plugins/org.dita.html5/xsl/rel-links.xsl
  src/main/plugins/org.dita.html5/xsl/svg-d.xsl
  src/main/plugins/org.dita.html5/xsl/syntax-braces.xsl
  src/main/plugins/org.dita.html5/xsl/tables.xsl
  src/main/plugins/org.dita.html5/xsl/task.xsl
  src/main/plugins/org.dita.html5/xsl/topic.xsl
  src/main/plugins/org.dita.pdf2/xsl/common/topicmergeImpl.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/bookmarks.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/flag-rules.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/flagging-from-preprocess.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/index.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/links.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/pr-domain.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/root-processing.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/tables.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/toc.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/topic.xsl
  src/main/plugins/org.dita.xhtml/xsl/dita2xhtml-util.xsl
  src/main/plugins/org.dita.xhtml/xsl/map2htmtoc/map2htmlImpl.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/get-meta.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/htmlflag.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/rel-links.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/svg-d.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/syntax-braces.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/tables.xsl
  src/main/plugins/org.dita.xhtml/xsl/xslhtml/taskdisplay.xsl
Labels: enhancement, internal

#3962 Fix for #3597, avoid NPE when reusing just row or cell in specialized components topic
  src/main/java/org/dita/dost/writer/NormalizeTableFilter.java
  src/test/java/org/dita/dost/writer/NormalizeTableFilterTest.java
  src/test/resources/NormalizeTableFilterTest/exp/onlyRows.dita
  src/test/resources/NormalizeTableFilterTest/src/onlyRows.dita
Labels: bug, priority/medium, preprocess

#3992 Allow empty sequence in named template
  src/main/plugins/org.dita.html5/xsl/reference.xsl
Labels: bug, priority/medium, enhancement
