Repository dita-ot/dita-ot, pull requests merged in 2022-12, with the labels that each got.

#4065 Fix `args.xhtml.toc.class` and `args.html5.toc.class`
  src/main/plugins/org.dita.html5/xsl/cover.xsl
  src/main/plugins/org.dita.xhtml/xsl/map2htmtoc/map2htmlcoverImpl.xsl
Labels: bug, plugin/xhtml, priority/medium, plugin/html5

#4073 Do not issue information messages if the filter has default exclude rules
  src/main/java/org/dita/dost/util/FilterUtils.java
  src/test/java/org/dita/dost/util/FilterUtilsTest.java
Labels: priority/medium, preprocess/filtering, enhancement

#4053 Fix flagging with specialized attribute
  src/main/java/org/dita/dost/util/FilterUtils.java
  src/test/java/org/dita/dost/util/FilterUtilsTest.java
Labels: bug, priority/medium, preprocess/filtering

#4082 Update syntax elements for DITA 2.0 class atts
  src/main/java/org/dita/dost/util/Constants.java
  src/main/plugins/org.dita.html5/xsl/syntax-braces.xsl
  src/main/plugins/org.dita.html5/xsl/syntax-svg.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/pr-domain.xsl
Labels: enhancement, DITA 2.0

#4078 Fix homebrew release workflow
  .github/workflows/bump-homebrew-formula.yml
  .github/workflows/release.yml
Labels: CI

#4080 Resolve <longdescref> @keyref references to @href
  src/main/java/org/dita/dost/writer/KeyrefPaser.java
Labels: bug, priority/medium, preprocess/keyref

#4088 Add file dependency tree to job state
  src/main/java/org/dita/dost/module/CleanPreprocessModule.java
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/module/reader/MapReaderModule.java
  src/main/java/org/dita/dost/util/Job.java
  src/main/java/org/dita/dost/util/UriGraph.java
  src/main/plugins/org.dita.base/build_preprocess_template.xml
Labels: feature

#4090 Refactor for Java 11 migration
  src/main/java/org/dita/dost/Processor.java
  src/main/java/org/dita/dost/ant/ExtensibleAntInvoker.java
  src/main/java/org/dita/dost/invoker/ConversionArguments.java
  src/main/java/org/dita/dost/invoker/DefaultLogger.java
  src/main/java/org/dita/dost/invoker/UsageBuilder.java
  src/main/java/org/dita/dost/module/CopyToModule.java
  src/main/java/org/dita/dost/module/DebugAndFilterModule.java
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/MoveLinksModule.java
  src/main/java/org/dita/dost/module/MoveMetaModule.java
  src/main/java/org/dita/dost/module/XsltModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/platform/Registry.java
  src/main/java/org/dita/dost/platform/SemVer.java
  src/main/java/org/dita/dost/project/ProjectFactory.java
  src/main/java/org/dita/dost/reader/KeyrefReader.java
  src/main/java/org/dita/dost/store/CacheStore.java
  src/main/java/org/dita/dost/store/StreamStore.java
  src/main/java/org/dita/dost/util/DITAOTCollator.java
  src/main/java/org/dita/dost/util/KeyScope.java
  src/main/java/org/dita/dost/util/LangUtils.java
  src/main/java/org/dita/dost/util/Pool.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/main/java/org/dita/dost/writer/AbstractChunkTopicParser.java
  src/main/java/org/dita/dost/writer/KeyrefPaser.java
  src/main/java/org/ditang/relaxng/defaults/RelaxNGDefaultsComponent.java
Labels: enhancement

#4091 Refactor to use Java 17 features
  src/main/java/org/dita/dost/ant/ExtensibleAntInvoker.java
  src/main/java/org/dita/dost/ant/PluginInstallTask.java
  src/main/java/org/dita/dost/chunk/ChunkModule.java
  src/main/java/org/dita/dost/chunk/ChunkOperation.java
  src/main/java/org/dita/dost/index/IndexTerm.java
  src/main/java/org/dita/dost/index/IndexTermTarget.java
  src/main/java/org/dita/dost/invoker/Arguments.java
  src/main/java/org/dita/dost/invoker/Main.java
  src/main/java/org/dita/dost/log/LoggerListener.java
  src/main/java/org/dita/dost/log/MessageUtils.java
  src/main/java/org/dita/dost/module/KeyrefModule.java
  src/main/java/org/dita/dost/module/MergeDitavalModule.java
  src/main/java/org/dita/dost/module/XsltModule.java
  src/main/java/org/dita/dost/module/filter/SubjectScheme.java
  src/main/java/org/dita/dost/module/reader/MapReaderModule.java
  src/main/java/org/dita/dost/platform/Alias.java
  src/main/java/org/dita/dost/platform/CheckTranstypeAction.java
  src/main/java/org/dita/dost/platform/ImportAntAction.java
  src/main/java/org/dita/dost/platform/ImportAntLibAction.java
  src/main/java/org/dita/dost/platform/ImportCatalogActionRelative.java
  src/main/java/org/dita/dost/platform/ImportStringsAction.java
  src/main/java/org/dita/dost/platform/ImportXSLAction.java
  src/main/java/org/dita/dost/platform/InsertAction.java
  src/main/java/org/dita/dost/platform/InsertDependsAction.java
  src/main/java/org/dita/dost/platform/Integrator.java
  src/main/java/org/dita/dost/platform/ListTranstypeAction.java
  src/main/java/org/dita/dost/platform/SemVerMatch.java
  src/main/java/org/dita/dost/platform/Value.java
  src/main/java/org/dita/dost/project/Project.java
  src/main/java/org/dita/dost/project/ProjectFactory.java
  src/main/java/org/dita/dost/reader/ChunkMapReader.java
  src/main/java/org/dita/dost/reader/ConrefPushReader.java
  src/main/java/org/dita/dost/reader/DitaValReader.java
  src/main/java/org/dita/dost/reader/DitamapIndexTermReader.java
  src/main/java/org/dita/dost/reader/GenListModuleReader.java
  src/main/java/org/dita/dost/reader/KeyrefReader.java
  src/main/java/org/dita/dost/util/FilterUtils.java
  src/main/java/org/dita/dost/util/Job.java
  src/main/java/org/dita/dost/util/KeyDef.java
  src/main/java/org/dita/dost/util/KeyScope.java
  src/main/java/org/dita/dost/util/SaxCache.java
  src/main/java/org/dita/dost/util/StringUtils.java
  src/main/java/org/dita/dost/util/XMLSerializer.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/main/java/org/dita/dost/writer/ConrefPushParser.java
  src/main/java/org/dita/dost/writer/ForceUniqueFilter.java
  src/main/java/org/dita/dost/writer/ImageMetadataFilter.java
  src/main/java/org/dita/dost/writer/KeyrefPaser.java
  src/main/java/org/dita/dost/writer/NormalizeCodeblock.java
  src/main/java/org/dita/dost/writer/NormalizeSimpleTableFilter.java
  src/main/java/org/dita/dost/writer/NormalizeTableFilter.java
  src/main/java/org/dita/dost/writer/ValidationFilter.java
  src/main/java/org/dita/dost/writer/include/IncludeResolver.java
  src/test/java/org/dita/dost/module/KeyrefModuleTest.java
  src/test/java/org/dita/dost/platform/FeaturesTest.java
  src/test/java/org/dita/dost/project/ProjectFactoryTest.java
  src/test/java/org/dita/dost/reader/TestKeyrefReader.java
  src/test/java/org/dita/dost/util/FilterUtilsTest.java
Labels: enhancement

#4092 Fix Javadoc issues
  src/main/java/org/dita/dost/ant/ExtensibleAntInvoker.java
  src/main/java/org/dita/dost/ant/UriBasenameTask.java
  src/main/java/org/dita/dost/ant/UriDirnameTask.java
  src/main/java/org/dita/dost/ant/types/JobSourceSet.java
  src/main/java/org/dita/dost/invoker/DefaultLogger.java
  src/main/java/org/dita/dost/module/BranchFilterModule.java
  src/main/java/org/dita/dost/module/MoveMetaModule.java
  src/main/java/org/dita/dost/platform/InsertAntActionRelative.java
  src/main/java/org/dita/dost/platform/InsertCatalogActionRelative.java
  src/main/java/org/dita/dost/platform/Integrator.java
  src/main/java/org/dita/dost/project/XmlReader.java
  src/main/java/org/dita/dost/reader/ConrefPushReader.java
  src/main/java/org/dita/dost/util/FilePathToURI.java
  src/main/java/org/dita/dost/util/URLUtils.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/main/java/org/dita/dost/writer/AbstractChunkTopicParser.java
  src/main/java/org/dita/dost/writer/ChunkTopicParser.java
  src/main/java/org/ditang/relaxng/defaults/RNCDefaultValues.java
  src/main/java/org/ditang/relaxng/defaults/RelaxNGDefaultValues.java
  src/main/java/org/ditang/relaxng/defaults/RelaxNGDefaultsComponent.java
  src/main/java/org/ditang/relaxng/defaults/Util.java
Labels: enhancement
