Repository dita-ot/dita-ot, pull requests merged in 2023-07, with the labels that each got.

#4226 Pass HDR, HDR, and FTR params as URL
  src/main/plugins/org.dita.html5/build_dita2html5_template.xml
  src/main/plugins/org.dita.xhtml/build_general_template.xml
Labels: bug, plugin/xhtml, plugin/html5

#4230 Fix running JUnit5 tests in Gradle
  build.gradle
  src/main/plugins/org.dita.htmlhelp/build.gradle
  src/main/plugins/org.dita.pdf2.fop/build.gradle
  src/main/plugins/org.dita.pdf2/build.gradle
  src/test/java/org/dita/dost/exception/DITAOTXMLErrorHandlerTest.java
Labels: build, CI

#4228 Update Jackson to fix snakeyaml security vulnerabilities
  build.gradle
Labels: priority/medium, dependency, security

#4243 Show development content in README
  README.markdown
  build.gradle
Labels: enhancement

#4239 Use correct cross-reference context when computing link description from `<shortdesc>` contents
  src/main/plugins/org.dita.base/xsl/preprocess/topicpullImpl.xsl
Labels: bug, priority/medium, preprocess

#4245 Update Guava 32.1.1
  build.gradle
Labels: priority/medium, enhancement, dependency

#4246 Update Logback and SLF4J
  build.gradle
Labels: priority/medium, enhancement, dependency, security

#4247 Update to Saxon-HE 12.3
  build.gradle
Labels: priority/medium, enhancement, dependency

#4248 Log exception with location
  src/main/java/org/dita/dost/exception/DITAOTXMLErrorHandler.java
Labels: bug, priority/medium

#4155 Insert <?ditaot dita-ot:usershortdesc?> in cases where it was missing
  src/main/plugins/org.dita.base/xsl/preprocess/topicpullImpl.xsl
Labels: bug, priority/medium, preprocess

#4237 Fix preprocess2 bugs
  src/main/java/org/dita/dost/exception/SAXExceptionWrapper.java
  src/main/java/org/dita/dost/module/KeyrefModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/module/reader/MapReaderModule.java
  src/main/java/org/dita/dost/module/reader/TopicReaderModule.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/test/java/org/dita/dost/IntegrationTest.java
  src/test/java/org/dita/dost/IntegrationTestPreprocess1.java
  src/test/java/org/dita/dost/IntegrationTestPreprocess2.java
  src/test/java/org/dita/dost/exception/SAXExceptionWrapperTest.java
  src/test/resources/bookmap-rng-based-validate/exp/preprocess/main.ditamap
  src/test/resources/bookmap-rng-based-validate/exp/preprocess/t1.dita
  src/test/resources/bookmap-rng-based-validate/exp/preprocess/t2.dita
  src/test/resources/bookmap-rng-based-validate/src/main.ditamap
  src/test/resources/bookmap-rng-based-validate/src/t1.dita
  src/test/resources/bookmap-rng-based-validate/src/t2.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-common0.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-common1.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-concept.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-next.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-parent.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-prerequisite.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-previous.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-reference.dita
  src/test/resources/conref/basic/exp/preprocess2/lang-task.dita
  src/test/resources/conref/conrefbreaksxref/exp/preprocess2/conrefbreaksxref.dita
  src/test/resources/conref/conrefbreaksxref/exp/preprocess2/conrefbreaksxreftarget.dita
  src/test/resources/conref/conrefbreaksxref/exp/preprocess2/subdir/conrefbreaksxrefsubdir.dita
Labels: bug, priority/medium, preprocess2

#4252 Fix PI generation in preprocess2
  src/main/java/org/dita/dost/module/CleanPreprocessModule.java
  src/main/java/org/dita/dost/writer/TopicCleanFilter.java
  src/test/java/org/dita/dost/writer/TopicCleanFilterTest.java
Labels: bug, priority/medium, preprocess2
