Repository dita-ot/dita-ot, pull requests merged in 2023-08, with the labels that each got.

#4255 Fix validating network file URI
  src/main/java/org/dita/dost/writer/ValidationFilter.java
  src/test/java/org/dita/dost/writer/ValidationFilterTest.java
Labels: bug, priority/low, preprocess

#4257 Fix getting file name from URI with space in file name #4064
  src/main/java/org/dita/dost/reader/ChunkMapReader.java
Labels: bug, priority/medium, preprocess/chunking

#4258 Fix conref in keydef value in preprocess2
  src/main/java/org/dita/dost/module/reader/TopicReaderModule.java
  src/test/java/org/dita/dost/module/reader/TopicReaderModuleTest.java
  src/test/resources/org/dita/dost/module/reader/TopicReaderModuleTest/src/root.ditamap
Labels: bug, priority/medium, preprocess2

#4259 Improve preprocess unit tests
  src/test/java/org/dita/dost/writer/KeyrefPaserTest.java
Labels: enhancement, internal

#4261 Process map conref during preprocess2 topic stage before keyref
  src/main/plugins/org.dita.base/build_preprocess2_template.xml
  src/main/plugins/org.dita.base/xsl/preprocess/conrefImpl.xsl
  src/main/plugins/org.dita.base/xsl/preprocess/map-conref_template.xsl
  src/test/java/org/dita/dost/IntegrationTest.java
  src/test/resources/keyref/keyword_conref/exp/preprocess/a.dita
  src/test/resources/keyref/keyword_conref/exp/preprocess/b.dita
  src/test/resources/keyref/keyword_conref/exp/preprocess/test.ditamap
  src/test/resources/keyref/keyword_conref/exp/preprocess2/a.dita
  src/test/resources/keyref/keyword_conref/exp/preprocess2/b.dita
  src/test/resources/keyref/keyword_conref/exp/preprocess2/test.ditamap
  src/test/resources/keyref/keyword_conref/src/a.dita
  src/test/resources/keyref/keyword_conref/src/b.dita
  src/test/resources/keyref/keyword_conref/src/test.ditamap
Labels: feature, priority/medium, preprocess/conref, preprocess2

#4264 Add preprocess integration test for subject scheme
  src/main/java/org/dita/dost/module/reader/MapReaderModule.java
  src/test/java/org/dita/dost/AbstractIntegrationTest.java
  src/test/java/org/dita/dost/IntegrationTest.java
  src/test/resources/subjectschema_case/exp/preprocess/simplemap.ditamap
  src/test/resources/subjectschema_case/exp/preprocess/simplescheme.ditamap
  src/test/resources/subjectschema_case/exp/preprocess/simpletopic.dita
  src/test/resources/subjectschema_case/src/filter.ditaval
  src/test/resources/subjectschema_case/src/simplemap.ditamap
  src/test/resources/subjectschema_case/src/simplescheme.ditamap
  src/test/resources/subjectschema_case/src/simpletopic.dita
Labels: enhancement, internal

#4267 Move teletype styling to Sass partial
  src/main/plugins/org.dita.html5/sass/domains/_hi-d.scss
  src/main/plugins/org.dita.html5/xsl/hi-d.xsl
Labels: priority/medium, enhancement, plugin/html5

#4268 Clean preprocess2 tests
  src/main/java/org/dita/dost/chunk/ChunkModule.java
  src/test/java/org/dita/dost/IntegrationTestPreprocess2.java
  src/test/resources/chunk_uplevel/exp/preprocess/common/reuse.dita
  src/test/resources/chunk_uplevel/exp/preprocess/main/chunkmefirst.dita
  src/test/resources/chunk_uplevel/exp/preprocess/main/chunkmetoo.dita
  src/test/resources/chunk_uplevel/exp/preprocess/main/chunkup.ditamap
  src/test/resources/chunk_uplevel/exp/preprocess/main/mixup/chunkmefirstSUBDIR.dita
  src/test/resources/chunk_uplevel/exp/preprocess/main/mixup/chunkmetooSUBDIR.dita
  src/test/resources/chunk_uplevel/src/common/reuse.dita
  src/test/resources/chunk_uplevel/src/main/chunkup.ditamap
  src/test/resources/chunk_uplevel/src/main/composite.dita
  src/test/resources/chunk_uplevel/src/main/mixup/composite.dita
  src/test/resources/reltableTextlink/exp/preprocess2/1132.ditamap
  src/test/resources/reltableTextlink/exp/preprocess2/booklist.dita
  src/test/resources/reltableTextlink/exp/preprocess2/booklist2.dita
  src/test/resources/resource_topic/exp/preprocess2/keys.ditamap
  src/test/resources/resource_topic/exp/preprocess2/resourceOnly.dita
  src/test/resources/resource_topic/exp/preprocess2/topic.dita
  src/test/resources/uplevelslink/exp/preprocess2/justthis.dita
  src/test/resources/uplevelslink/exp/preprocess2/uplevel-in-topic.ditamap
Labels: enhancement, internal
