Repository dita-ot/dita-ot, pull requests merged in 2023-09, with the labels that each got.

#4276 ignore `<fn>` elements when computing link text for a target element
  src/main/plugins/org.dita.base/xsl/preprocess/topicpullImpl.xsl
  src/main/plugins/org.dita.pdf2/xsl/fo/tables.xsl
Labels: bug

#4279 Update to xmlresolver 5.2.1
  build.gradle
Labels: bug, dependency

#4280 Add tests for cascading metadata in duplicate topicrefs
  src/test/java/org/dita/dost/reader/MapMetaReaderTest.java
  src/test/resources/MapMetaReaderTest/exp/base/test.ditamap
  src/test/resources/MapMetaReaderTest/exp/duplicate/test.ditamap
  src/test/resources/MapMetaReaderTest/exp/locktitle/test.ditamap
  src/test/resources/MapMetaReaderTest/src/base/a.xml
  src/test/resources/MapMetaReaderTest/src/base/b.xml
  src/test/resources/MapMetaReaderTest/src/base/c.xml
  src/test/resources/MapMetaReaderTest/src/base/d.xml
  src/test/resources/MapMetaReaderTest/src/base/nest.xml
  src/test/resources/MapMetaReaderTest/src/base/test.ditamap
  src/test/resources/MapMetaReaderTest/src/duplicate/a.xml
  src/test/resources/MapMetaReaderTest/src/duplicate/test.ditamap
  src/test/resources/MapMetaReaderTest/src/locktitle/a.xml
  src/test/resources/MapMetaReaderTest/src/locktitle/test.ditamap
Labels: preprocess, enhancement, internal

#4283 Refactor metadata cascade code
  src/main/java/org/dita/dost/reader/MapMetaReader.java
  src/main/java/org/dita/dost/util/XMLUtils.java
Labels: preprocess, enhancement, internal

#4284 Fix metadata cascade
  src/main/java/org/dita/dost/reader/MapMetaReader.java
  src/test/java/org/dita/dost/IntegrationTestPreprocess2.java
  src/test/java/org/dita/dost/TestUtils.java
  src/test/java/org/dita/dost/reader/MapMetaReaderTest.java
  src/test/resources/MapMetaReaderTest/exp/duplicate-single/test.ditamap
  src/test/resources/MapMetaReaderTest/exp/duplicate/test.ditamap
  src/test/resources/MapMetaReaderTest/exp/locktitle/test.ditamap
  src/test/resources/MapMetaReaderTest/src/duplicate-single/a.xml
  src/test/resources/MapMetaReaderTest/src/duplicate-single/test.ditamap
  src/test/resources/copyto/basic/exp/preprocess/TC2.ditamap
  src/test/resources/copyto/basic/exp/preprocess/newtest3.dita
Labels: bug, preprocess
