Repository dita-ot/dita-ot, pull requests merged in 2023-05, with the labels that each got.

#4180 Add test for MapReaderModule
  src/main/java/org/dita/dost/module/reader/TopicReaderModule.java
  src/test/java/org/dita/dost/module/reader/MapReaderModuleTest.java
  src/test/resources/MapReaderModuleTest/src/root.ditamap
  src/test/resources/MapReaderModuleTest/src/submap.ditamap
  src/test/resources/MapReaderModuleTest/src/subtopic.dita
  src/test/resources/MapReaderModuleTest/src/topic.dita
Labels: preprocess2, internal

#4186 Fix DITA-OT 4.x compatibility with HTMLHelp
  src/main/plugins/org.dita.htmlhelp/build_dita2htmlhelp_template.xml
Labels: bug, plugin/htmlhelp, priority/medium

#4182 Update to Ant 1.10.13
  build.gradle
  src/main/plugins/org.dita.pdf2/build.gradle
Labels: priority/medium, enhancement, dependency

#4185 Fix for #4184, avoid creating nested <desc> elements
  src/main/plugins/org.dita.base/xsl/preprocess/topicpullImpl.xsl
Labels: bug, priority/medium, preprocess

#4183 Update to FOP 2.8
  src/main/plugins/org.dita.pdf2.fop/build.gradle
  src/main/plugins/org.dita.pdf2.fop/plugin.xml
Labels: priority/medium, enhancement, plugin/pdf/fop, dependency

#4188 Support alternative DITA formats as conref target
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/module/reader/MapReaderModule.java
  src/main/java/org/dita/dost/module/reader/TopicReaderModule.java
  src/main/java/org/dita/dost/reader/GenListModuleReader.java
Labels: bug, preprocess, plugin/lwdita

#4130 Use Saxon-HE 12
  build.gradle
  gradle/dist.gradle
  src/main/java/org/dita/dost/ant/XMLCatalogAdapter.java
  src/main/java/org/dita/dost/module/CleanPreprocessModule.java
  src/main/java/org/dita/dost/module/KeyrefModule.java
  src/main/java/org/dita/dost/module/MaprefModule.java
  src/main/java/org/dita/dost/module/MoveLinksModule.java
  src/main/java/org/dita/dost/module/MoveMetaModule.java
  src/main/java/org/dita/dost/module/SourceReaderModule.java
  src/main/java/org/dita/dost/module/TopicMergeModule.java
  src/main/java/org/dita/dost/module/XsltModule.java
  src/main/java/org/dita/dost/store/CacheStore.java
  src/main/java/org/dita/dost/store/StreamStore.java
  src/main/java/org/dita/dost/util/CatalogUtils.java
  src/main/java/org/dita/dost/util/ChainedURIResolver.java
  src/main/java/org/dita/dost/util/DelegatingURIResolver.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/main/plugins/org.dita.base/xsl/common/output-message.xsl
  src/main/plugins/org.dita.htmlhelp/build.gradle
  src/main/plugins/org.dita.pdf2/build.gradle
  src/main/plugins/org.dita.pdf2/src/com/idiominc/ws/opentopic/fo/i18n/PreprocessorTask.java
  src/test/java/org/dita/dost/AbstractIntegrationTest.java
  src/test/java/org/dita/dost/util/XMLUtilsTest.java
  src/test/java/org/dita/dost/util/XSpecTest.java
  src/test/resources/bookmap7/src/chapter3.ditamap
  src/test/resources/mapref/mapref_reltables/src/main-1.dita
  src/test/resources/mapref/mapref_reltables/src/main-2.dita
  src/test/resources/mapref/mapref_reltables/src/main-3.dita
  src/test/resources/mapref/mapref_reltables/src/main-4.dita
  src/test/resources/mapref/mapref_reltables/src/main-5.dita
  src/test/resources/mapref/mapref_reltables/src/main-6.dita
  src/test/resources/mapref/mapref_reltables/src/main.ditamap
  src/test/resources/mapref/mapref_reltables/src/mapref2-1.dita
  src/test/resources/mapref/mapref_reltables/src/mapref2-2.dita
  src/test/resources/mapref/mapref_reltables/src/mapref2-3.dita
  src/test/resources/mapref/mapref_reltables/src/mapref2-4.dita
  src/test/resources/mapref/mapref_reltables/src/mapref2-5.dita
  src/test/resources/mapref/mapref_reltables/src/mapref2.ditamap
  src/test/resources/mapref/mapref_reltables/src/reltable.ditamap
  src/test/resources/mapref/mapref_reltables/src/subdir/mapref1-1.dita
  src/test/resources/mapref/mapref_reltables/src/subdir/mapref1-2.dita
  src/test/resources/mapref/mapref_reltables/src/subdir/mapref1-3.dita
  src/test/resources/mapref/mapref_reltables/src/subdir/mapref1-4.dita
  src/test/resources/mapref/mapref_reltables/src/subdir/mapref1-5.dita
  src/test/resources/mapref/mapref_reltables/src/subdir/mapref1.ditamap
Labels: priority/medium, enhancement, dependency

#4194 Update PDF Theme plug-in to version 0.7.0
  build.gradle
Labels: enhancement, dependency

#4187 Throw exception In strict processing mode when error is logged from XSLT
  src/main/java/org/dita/dost/ant/ExtensibleAntInvoker.java
  src/main/java/org/dita/dost/module/AbstractPipelineModule.java
  src/main/java/org/dita/dost/module/AbstractPipelineModuleImpl.java
  src/main/java/org/dita/dost/module/MaprefModule.java
  src/main/java/org/dita/dost/module/MoveLinksModule.java
  src/main/java/org/dita/dost/module/MoveMetaModule.java
  src/main/java/org/dita/dost/module/TopicMergeModule.java
  src/main/java/org/dita/dost/module/XsltModule.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/test/java/org/dita/dost/module/DummyPipelineModule.java
  src/test/java/org/dita/dost/util/XMLUtilsTest.java
Labels: bug, priority/medium

#4197 Update Gradle wrapper to 7.6.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: enhancement, build

#4205 Support SAX properties for custom parsers
  src/main/java/org/dita/dost/module/DebugAndFilterModule.java
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/SourceReaderModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/util/Constants.java
  src/main/java/org/dita/dost/util/XMLUtils.java
  src/test/java/org/dita/dost/reader/CustomXMLReader.java
  src/test/java/org/dita/dost/util/XMLUtilsTest.java
  src/test/resources/org.dita.dost.platform/plugin.properties
Labels: feature, priority/medium, preprocess
