Repository dita-ot/dita-ot, pull requests merged in 2023-04, with the labels that each got.

#4159 Support custom parse for start map
  src/main/java/org/dita/dost/module/GenMapAndTopicListModule.java
  src/main/java/org/dita/dost/module/reader/AbstractReaderModule.java
  src/main/java/org/dita/dost/module/reader/MapReaderModule.java
  src/main/java/org/dita/dost/module/reader/TopicReaderModule.java
Labels: feature, preprocess

#4160 Fix bug in non-DITA start map processing
  src/main/java/org/dita/dost/module/DebugAndFilterModule.java
Labels: priority/medium, preprocess, enhancement

#4161 Update LwDITA plug-in from 3.3 to 5.1
  build.gradle
Labels: priority/medium, enhancement, dependency, plugin/lwdita

#4152 #3903 strip fragments when determining what to branch-filter
  src/main/java/org/dita/dost/module/BranchFilterModule.java
Labels: bug, priority/medium, preprocess/branch-filtering

#3968 Fix for #3967, cross-reference to footnote is double-wrapped in `<sup>`
  src/main/plugins/org.dita.base/xsl/preprocess/topicpullImpl.xsl
Labels: bug

#4132 Preprocess2 non-dita files not copied correctly to output dir
  src/main/plugins/org.dita.base/build_preprocess2_template.xml
Labels: bug, priority/medium, preprocess2
