Repository dita-ot/dita-ot, pull requests merged in 2023-06, with the labels that each got.

#4210 Update bundled LwDITA plug-in to version 5.5
  build.gradle
Labels: priority/medium, enhancement, dependency

#4211 Update `outer` parameter descriptions per #4201
  src/main/plugins/org.dita.base/plugin.xml
Labels: enhancement

#4214 Bump xdita grammar to latest, v0.3.0
  build.gradle
Labels: dita standard, plugin/lwdita

#4199 Refactor CLI error message and usage print
  src/main/build.xml
  src/main/java/org/dita/dost/Processor.java
  src/main/java/org/dita/dost/invoker/Arguments.java
  src/main/java/org/dita/dost/invoker/CliException.java
  src/main/java/org/dita/dost/invoker/ConversionArguments.java
  src/main/java/org/dita/dost/invoker/DeliverablesArguments.java
  src/main/java/org/dita/dost/invoker/InstallArguments.java
  src/main/java/org/dita/dost/invoker/Main.java
  src/main/java/org/dita/dost/invoker/PluginsArguments.java
  src/main/java/org/dita/dost/invoker/TranstypesArguments.java
  src/main/java/org/dita/dost/invoker/UninstallArguments.java
  src/main/java/org/dita/dost/invoker/UsageBuilder.java
  src/main/java/org/dita/dost/invoker/VersionArguments.java
  src/main/plugins/org.dita.base/build_template.xml
Labels: enhancement, CLI

#4217 Add support for .ditaotrc
  src/main/java/org/dita/dost/invoker/Main.java
Labels: priority/medium, enhancement, CLI
