Repository dita-ot/dita-ot, pull requests merged in 2025-08, with the labels that each got.

#4705 Fix force unique filter attribute stack
  src/main/java/org/dita/dost/writer/ForceUniqueFilter.java
Labels: bug, preprocess

#4688 fix node executable path on Windows
  build.gradle
Labels: bug, build, internal

#4708 Fix attribute stack bugs
  src/main/java/org/dita/dost/reader/MergeMapParser.java
  src/main/java/org/dita/dost/writer/ForceUniqueFilter.java
Labels: bug, plugin/pdf, preprocess
