Repository dita-ot/dita-ot, pull requests merged in 2025-03, with the labels that each got.

#4569 Enhance LinkFilter to support the copy-to attribute as priority over href attribute
  src/main/java/org/dita/dost/writer/LinkFilter.java
  src/test/java/org/dita/dost/writer/LinkFilterTest.java
Labels: bug, preprocess2

#4592 Support format option for validate
  src/main/java/org/dita/dost/invoker/ValidateArguments.java
Labels: enhancement, CLI

#4583 Add support for multiple deliverable options
  src/main/java/org/dita/dost/invoker/ConversionArguments.java
  src/main/java/org/dita/dost/invoker/Main.java
  src/main/java/org/dita/dost/invoker/ValidateArguments.java
  src/main/resources/cli_en_US.properties
  src/test/java/org/dita/dost/invoker/ConversionArgumentsTest.java
  src/test/java/org/dita/dost/invoker/MainProjectTest.java
Labels: enhancement, CLI

#4594 Fix CLI default output directory
  .github/workflows/gradle-wrapper-validation.yml
  src/main/java/org/dita/dost/invoker/Main.java
Labels: bug, CLI

#4595 Update Saxon and Ant dependencies
  build.gradle
  src/main/plugins/org.dita.htmlhelp/build.gradle
  src/main/plugins/org.dita.pdf2/build.gradle
Labels: enhancement, dependency

#4599 Add lines element is block function
  src/main/plugins/org.dita.html5/xsl/topic.xsl
Labels: bug, plugin/html5

#4588 Update logback version for security fixes
  build.gradle
Labels: priority/medium, dependency, security

#4603 Fix subcommand backwards compatibility bug
  src/main/java/org/dita/dost/invoker/ArgumentParser.java
  src/test/java/org/dita/dost/invoker/ArgumentParserTest.java
Labels: bug, CLI

#4606 Fix basedir with uplevels resource-only resources
  src/main/java/org/dita/dost/module/CleanPreprocessModule.java
  src/test/java/org/dita/dost/module/CleanPreprocessModuleTest.java
Labels: bug, preprocess

#4577 Fix combine chunk behaviour
  src/main/java/org/dita/dost/chunk/ChunkModule.java
  src/test/java/org/dita/dost/chunk/ChunkModuleTest.java
  src/test/resources/org/dita/dost/chunk/ChunkModuleTest/exp/combine/.job.xml
  src/test/resources/org/dita/dost/chunk/ChunkModuleTest/exp/combine/a.dita
  src/test/resources/org/dita/dost/chunk/ChunkModuleTest/exp/combine/c.dita
  src/test/resources/org/dita/dost/chunk/ChunkModuleTest/exp/combine/combine.ditamap
  src/test/resources/org/dita/dost/chunk/ChunkModuleTest/src/combine/combine.ditamap
  src/test/resources/org/dita/dost/chunk/ChunkModuleTest/src/combine/d.dita
Labels: bug, preprocess/chunking, DITA 2.0

#4609 Use docker actions to build and push Docker
  .github/workflows/release.yml
Labels: bug, CI, docker
