Repository dita-ot/dita-ot, pull requests merged in 2025-07, with the labels that each got.

#4664 Add unit tests for coderef
  src/main/java/org/dita/dost/writer/include/AllRange.java
  src/main/java/org/dita/dost/writer/include/AnchorRange.java
  src/main/java/org/dita/dost/writer/include/LineNumberRange.java
  src/test/java/org/dita/dost/writer/include/AllRangeTest.java
  src/test/java/org/dita/dost/writer/include/AnchorRangeTest.java
  src/test/java/org/dita/dost/writer/include/LineNumberRangeTest.java
Labels: enhancement, internal

#4666 #4447 follow-up /refactor_gradle
  build.gradle
  gradle/dist.gradle
  settings.gradle
  src/main/plugins/org.dita.htmlhelp/build.gradle
  src/main/plugins/org.dita.pdf2.fop/build.gradle
  src/main/plugins/org.dita.pdf2/build.gradle
Labels: enhancement, build, internal

#4671 make errorCount and warnCount failures more informative
  src/test/java/org/dita/dost/AbstractIntegrationTest.java
Labels: enhancement, internal

#4673 Improve integration test results
  src/test/java/org/dita/dost/AbstractIntegrationTest.java
  src/test/java/org/dita/dost/TestUtils.java
Labels: enhancement, build

#4675 fix html5 uplevels3 CSS path in index.html
  src/main/java/org/dita/dost/module/CleanPreprocessModule.java
  src/main/java/org/dita/dost/writer/MapCleanFilter.java
  src/main/java/org/dita/dost/writer/TopicCleanFilter.java
  src/test/resources/html5_uplevels3_nav_toc_full/exp/html5/maps/index.html
  src/test/resources/html5_uplevels3_nav_toc_partial/exp/html5/maps/index.html
Labels: bug, preprocess
